;;;; commensura — Frink-inspired exact unit conversion for Clojure.
;;;; Copyright (C) 2026  crinklywrappr
;;;;
;;;; This program is free software: you can redistribute it and/or modify it
;;;; under the terms of the GNU General Public License as published by the Free
;;;; Software Foundation, either version 3 of the License, or (at your option)
;;;; any later version.  Distributed WITHOUT ANY WARRANTY; see the GNU General
;;;; Public License <https://www.gnu.org/licenses/> for details.
;;;;
;;;; GENERATED by commensura.units.gen from resources/commensura/units.edn.
;;;; DO NOT EDIT BY HAND — regenerate with: clojure -T:build gen-units

(ns commensura.dimensions
  "GENERATED dimension-name index (dims-map -> name) from units.edn's |||
  declarations — see commensura.units.gen. Consulted by quantity's printer.")

(def names
{{:current 2, :time 4, :mass -1, :length -3} "permittivity",
 {:length 1, :time -2} "acceleration",
 {:mass 1, :length -2} "area density",
 {:mass 1, :length 2, :time -2, :amount_of_substance -1}
 "molar energy",
 {:length 1, :mass 1, :time -2} "force",
 {:amount_of_substance 1, :mass -1} "concentration by mass",
 {:length 2, :mass 1, :time -3} "power",
 {:length 2, :mass 1, :time -2} "energy",
 {:temperature 1, :mass -1, :time 3} "thermal insulance",
 {:length 1, :mass -1} "reciprocal linear mass density",
 {:length 2, :time -2} "specific energy",
 {:mass 1, :length 1, :time -3, :current -1} "electric field strength",
 {:mass -1, :length 3, :time -2} "gravitational constant",
 {:length -2, :luminous_intensity 1} "illuminance",
 {:length 2, :mass 1, :time -1} "angular momentum",
 {:length 2, :time -2, :temperature -1} "specific heat capacity",
 {:mass -1, :length -2, :time 2, :current 2} "magnetic reluctance",
 {:current 2, :time 4, :mass -1, :length -2} "capacitance",
 {:mass 1, :time -3} "heat flux density",
 {:current 1, :time 1, :length -3} "electric charge density",
 {:mass 1, :length -1, :time -1} "viscosity",
 {:mass -1, :length 1, :time 1} "reciprocal viscosity",
 {:length 2, :time -1} "kinematic viscosity",
 {} "dimensionless",
 {:mass 1,
  :length 2,
  :time -2,
  :amount_of_substance -1,
  :temperature -1}
 "molar heat capacity",
 {:length -3, :mass 1} "mass density",
 {:length 2, :current 1} "magnetic moment",
 {:mass 1, :length 1, :time -3, :temperature -1}
 "thermal conductivity",
 {:length 3, :mass -1} "specific volume",
 {:current 1, :length -2} "electric current density",
 {:mass 1, :time -2, :current -1} "magnetic flux density",
 {:time -1} "frequency",
 {:mass 1, :time -2} "surface tension",
 {:length 2} "area",
 {:current 2, :mass -1, :length -2, :time 3} "electric conductance",
 {:mass 1, :time -3, :temperature -1} "thermal conductance",
 {:length -1, :mass 1, :time -2} "pressure",
 {:mass 1, :amount_of_substance -1} "molar mass",
 {:current 1, :time 1} "charge",
 {:mass 1, :length 2, :time -2, :temperature -1} "heat capacity",
 {:amount_of_substance 1, :length -3} "concentration by volume",
 {:length 3, :time -1} "flow",
 {:mass 1, :length -1} "linear mass density",
 {:luminous_intensity 1, :time 1} "luminous energy",
 {:mass 1, :length 1, :time -2, :current -2} "permeability",
 {:current -2, :time -4, :mass 1, :length 3} "electric force constant",
 {:length 1, :mass 1, :time -1} "momentum",
 {:length 1, :time -1} "velocity",
 {:currency 1, :mass -1} "price per mass",
 {:mass 1, :length 2, :time -2, :current -2} "inductance",
 {:mass 1, :length 2, :time -3, :current -1} "electric potential",
 {:mass 1, :length 2, :time -3, :current -2} "electric resistance",
 {:current 1, :time 1, :length 1} "electrical dipole moment",
 {:current 1, :length -1} "magnetic field strength",
 {:length 3} "volume",
 {:length 2, :mass 1} "moment of inertia",
 {:length 3, :amount_of_substance -1} "molar volume",
 {:time -3, :mass 1, :temperature -4} "radiative power constant",
 {:mass 1, :length 3, :time -3, :current -2} "electric resistivity",
 {:current 1, :time 1, :length -2} "surface charge density",
 {:temperature 1, :mass -1, :length -2, :time 3} "thermal resistance",
 {:current 2, :mass -1, :length -3, :time 3} "electric conductivity",
 {:length -2, :time 2, :mass -1, :current 1} "josephson constant",
 {:length -1, :temperature 1, :mass -1, :time 3} "thermal resistivity",
 {:mass 1, :length 2, :time -2, :current -1} "magnetic flux"})
