;;;; commensura — Frink-inspired exact unit conversion for Clojure.
;;;; Copyright (C) 2026  crinklywrappr
;;;;
;;;; This program is free software: you can redistribute it and/or modify it
;;;; under the terms of the GNU General Public License as published by the Free
;;;; Software Foundation, either version 3 of the License, or (at your option)
;;;; any later version.  Distributed WITHOUT ANY WARRANTY; see the GNU General
;;;; Public License <https://www.gnu.org/licenses/> for details.
;;;;
;;;; GENERATED by commensura.units.gen from resources/commensura/units.edn.
;;;; DO NOT EDIT BY HAND — regenerate with: clojure -T:build gen-units

(ns commensura.dimensions
  "GENERATED dimension-name index (dims-map -> name) from units.edn's |||
  declarations — see commensura.units.gen. Consulted by quantity's printer.")

(def names
{{:current 2, :time 4, :mass -1, :length -3} "permittivity",
 {:length 1, :time -2} "acceleration",
 {:mass 1, :length -2} "area_density",
 {:mass 1, :length 2, :time -2, :amount_of_substance -1}
 "molar_energy",
 {:length 1, :mass 1, :time -2} "force",
 {:amount_of_substance 1, :mass -1} "concentration_by_mass",
 {:length 2, :mass 1, :time -3} "power",
 {:length 2, :mass 1, :time -2} "energy",
 {:temperature 1, :mass -1, :time 3} "thermal_insulance",
 {:length 1, :mass -1} "reciprocal_linear_mass_density",
 {:length 2, :time -2} "specific_energy",
 {:mass 1, :length 1, :time -3, :current -1} "electric_field_strength",
 {:mass -1, :length 3, :time -2} "gravitational_constant",
 {:length -2, :luminous_intensity 1} "illuminance",
 {:length 2, :mass 1, :time -1} "angular_momentum",
 {:length 2, :time -2, :temperature -1} "specific_heat_capacity",
 {:mass -1, :length -2, :time 2, :current 2} "magnetic_reluctance",
 {:current 2, :time 4, :mass -1, :length -2} "capacitance",
 {:mass 1, :time -3} "heat_flux_density",
 {:current 1, :time 1, :length -3} "electric_charge_density",
 {} "dimensionless",
 {:mass 1,
  :length 2,
  :time -2,
  :amount_of_substance -1,
  :temperature -1}
 "molar_heat_capacity",
 {:length -3, :mass 1} "mass_density",
 {:length 2, :current 1} "magnetic_moment",
 {:mass 1, :length 1, :time -3, :temperature -1}
 "thermal_conductivity",
 {:length 3, :mass -1} "specific_volume",
 {:current 1, :length -2} "electric_current_density",
 {:mass 1, :time -2, :current -1} "magnetic_flux_density",
 {:time -1} "frequency",
 {:mass 1, :time -2} "surface_tension",
 {:length 2} "area",
 {:current 2, :mass -1, :length -2, :time 3} "electric_conductance",
 {:mass 1, :time -3, :temperature -1} "thermal_conductance",
 {:length -1, :mass 1, :time -2} "pressure",
 {:mass 1, :amount_of_substance -1} "molar_mass",
 {:current 1, :time 1} "charge",
 {:mass 1, :length 2, :time -2, :temperature -1} "heat_capacity",
 {:length 3, :time -1} "flow",
 {:mass 1, :length -1} "linear_mass_density",
 {:luminous_intensity 1, :time 1} "luminous_energy",
 {:mass 1, :length 1, :time -2, :current -2} "permeability",
 {:current -2, :time -4, :mass 1, :length 3} "electric_force_constant",
 {:length 1, :mass 1, :time -1} "momentum",
 {:length 1, :time -1} "velocity",
 {:currency 1, :mass -1} "price_per_mass",
 {:mass 1, :length 2, :time -2, :current -2} "inductance",
 {:mass 1, :length 2, :time -3, :current -1} "electric_potential",
 {:mass 1, :length 2, :time -3, :current -2} "electric_resistance",
 {:current 1, :length -1} "magnetic_field_strength",
 {:length 3} "volume",
 {:length 2, :mass 1} "moment_of_inertia",
 {:length 3, :amount_of_substance -1} "molar_volume",
 {:time -3, :mass 1, :temperature -4} "radiative_power_constant",
 {:mass 1, :length 3, :time -3, :current -2} "electric_resistivity",
 {:current 1, :time 1, :length -2} "surface_charge_density",
 {:temperature 1, :mass -1, :length -2, :time 3} "thermal_resistance",
 {:current 2, :mass -1, :length -3, :time 3} "electric_conductivity",
 {:length -2, :time 2, :mass -1, :current 1} "josephson_constant",
 {:length -1, :temperature 1, :mass -1, :time 3} "thermal_resistivity",
 {:mass 1, :length 2, :time -2, :current -1} "magnetic_flux"})
