;;;; commensura — Frink-inspired exact unit conversion for Clojure.
;;;; Copyright (C) 2026  crinklywrappr
;;;;
;;;; This program is free software: you can redistribute it and/or modify it
;;;; under the terms of the GNU General Public License as published by the Free
;;;; Software Foundation, either version 3 of the License, or (at your option)
;;;; any later version.  Distributed WITHOUT ANY WARRANTY; see the GNU General
;;;; Public License <https://www.gnu.org/licenses/> for details.

(ns commensura.units.gen
  "DEV-ONLY: generate src/commensura/units.clj (the ~2000 callable unit vars)
  from resources/commensura/units.edn. Run with: clojure -T:build gen-units"
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.pprint :as pp]
            [clojure.string :as str]))

(def ^:private safe-name-re #"^[A-Za-z_$][A-Za-z0-9_$?!*<>=-]*$")
(defn- safe? [n] (boolean (re-matches safe-name-re n)))
(defn- core? [n] (boolean (ns-resolve 'clojure.core (symbol n))))

;; SI (+binary-adjacent) decimal prefixes we expose as callable functions.
(def ^:private prefix-fn-names
  ["deka" "hecto" "kilo" "mega" "giga" "tera" "peta" "exa" "zetta" "yotta" "ronna" "quetta"
   "deci" "centi" "milli" "micro" "nano" "pico" "femto" "atto" "zepto" "yocto" "ronto" "quecto"])

;; Curated short prefixed forms the abbreviations expect (Frink stores only the
;; long names). [var-name base-unit multiplier]
(def ^:private prefixed
  [["km" "meter" 1000] ["cm" "meter" 1/100] ["mm" "meter" 1/1000] ["nm" "meter" 1/1000000000]
   ["mg" "gram" 1/1000] ["kg" "gram" 1000]
   ["mL" "liter" 1/1000] ["ml" "liter" 1/1000] ["cL" "liter" 1/100] ["kL" "liter" 1000]
   ["kJ" "joule" 1000] ["MJ" "joule" 1000000]
   ["mW" "watt" 1/1000] ["kW" "watt" 1000] ["MW" "watt" 1000000]
   ["mV" "volt" 1/1000] ["kV" "volt" 1000]
   ["kPa" "pascal" 1000] ["MPa" "pascal" 1000000]
   ["kHz" "hertz" 1000] ["MHz" "hertz" 1000000] ["GHz" "hertz" 1000000000]
   ["kN" "newton" 1000]
   ["kiloton" "ton" 1000] ["megaton" "ton" 1000000]])

(def ^:private header
  ";;;; commensura — Frink-inspired exact unit conversion for Clojure.
;;;; Copyright (C) 2026  crinklywrappr
;;;;
;;;; This program is free software: you can redistribute it and/or modify it
;;;; under the terms of the GNU General Public License as published by the Free
;;;; Software Foundation, either version 3 of the License, or (at your option)
;;;; any later version.  Distributed WITHOUT ANY WARRANTY; see the GNU General
;;;; Public License <https://www.gnu.org/licenses/> for details.
;;;;
;;;; GENERATED by commensura.units.gen from resources/commensura/units.edn.
;;;; DO NOT EDIT BY HAND — regenerate with: clojure -X:build gen-units")

(def ^:private helpers
  "(defn- mk-prefix [value]
  (fn prefixer [x] (qty/scale (if (or (qty/unit? x) (qty/quantity? x)) x (qty/scalar x)) value)))")

(defn generate!
  ([] (generate! "resources/commensura/units.edn" "src/commensura/units.clj"))
  ([in out]
   (let [{:keys [units prefixes dimension-names]} (edn/read-string (slurp in))
         name-set  (set (keys units))
         emitted   (atom #{})
         emit!     (fn [n] (swap! emitted conj n) n)
         ;; 1. base unit vars (ascii-safe)
         unit-lines (vec (for [n (sort (filter safe? (keys units)))
                          :let [{:keys [factor dims doc]} (units n)]]
                      (do (emit! n)
                          (if doc
                            (format "(defunit %s\n  %s\n  %s %s)" n (pr-str doc) (pr-str factor) (pr-str dims))
                            (format "(defunit %s %s %s)" n (pr-str factor) (pr-str dims))))))
         ;; 2. curated short prefixed vars
         prefixed-lines (vec (for [[v base mult] prefixed
                              :let [u (units base)]
                              :when (and u (not (@emitted v)))]
                          (do (emit! v)
                              (format "(defunit %s %s %s)"
                                      v (pr-str (* mult (:factor u))) (pr-str (:dims u))))))
         ;; 3. plural aliases (append s) for everything emitted so far
         plural-lines (vec (for [n (sort @emitted)
                            :let [p (str n "s")]
                            :when (and (safe? p) (not (name-set p)) (not (@emitted p))
                                       (not (str/ends-with? n "s")))]
                        (do (emit! p) (format "(def %s %s)" p n))))
         ;; 4. prefix functions
         prefix-lines (vec (for [p prefix-fn-names
                            :let [val (prefixes p)]
                            :when (and val (not (@emitted p)))]
                        (do (emit! p) (format "(def %s (mk-prefix %s))" p (pr-str val)))))
         exclusions (->> @emitted (filter core?) (map symbol) sort vec)
         ns-form (format "(ns commensura.units\n  \"Generated callable unit vars — see commensura.units.gen. Use via :as u.\"\n  (:refer-clojure :exclude %s)\n  (:require [commensura.quantity :as qty]\n            [commensura.core :refer [defunit]]))"
                         (pr-str exclusions))]
     (with-open [w (io/writer out)]
       (.write w (str header "\n\n" ns-form "\n\n" helpers "\n\n"
                      ";; ---- base units ----\n" (str/join "\n" unit-lines) "\n\n"
                      ";; ---- common prefixed units ----\n" (str/join "\n" prefixed-lines) "\n\n"
                      ";; ---- plural aliases ----\n" (str/join "\n" plural-lines) "\n\n"
                      ";; ---- prefix functions ----\n" (str/join "\n" prefix-lines) "\n")))
     ;; also bake the |||-dimension-name index into a generated leaf ns
     ;; (so the runtime never reads the EDN — it stays a pure build-time IR).
     (with-open [w (io/writer "src/commensura/dimensions.clj")]
       (.write w (str header "\n\n"
                      "(ns commensura.dimensions\n"
                      "  \"GENERATED dimension-name index (dims-map -> name) from units.edn's |||\n"
                      "  declarations — see commensura.units.gen. Consulted by quantity's printer.\")\n\n"
                      "(def names\n"
                      (str/trimr (with-out-str (pp/pprint dimension-names)))
                      ")\n")))
     (println (format "wrote %s : %d unit vars, %d prefixed, %d plurals, %d prefix-fns, %d excluded"
                      out (count unit-lines) (count prefixed-lines) (count plural-lines)
                      (count prefix-lines) (count exclusions)))
     (println (format "wrote src/commensura/dimensions.clj : %d dimension names" (count dimension-names)))
     out)))

(defn -main [& _] (generate!))
