;;;; commensura — Frink-inspired exact unit conversion for Clojure.
;;;; Copyright (C) 2026  crinklywrappr
;;;;
;;;; This program is free software: you can redistribute it and/or modify it
;;;; under the terms of the GNU General Public License as published by the Free
;;;; Software Foundation, either version 3 of the License, or (at your option)
;;;; any later version.  Distributed WITHOUT ANY WARRANTY; see the GNU General
;;;; Public License <https://www.gnu.org/licenses/> for details.

(ns commensura.currency.gen
  "DEV-ONLY. Generate `src/commensura/currency.clj` from `resources/commensura/currency-codes.edn` —
  one discoverable fn per currency code, each delegating to `commensura.currency.rates/of`."
  (:require [clojure.edn :as edn]
            [clojure.string :as str]))

(def ^:private codes-path "resources/commensura/currency-codes.edn")
(def ^:private out-path   "src/commensura/currency.clj")

(defn- legal-sym?
  "A code emittable as a plain Clojure fn name (alpha-led, alphanumeric). Others (e.g. `1INCH`) are
  skipped and remain reachable via `commensura.currency.rates/of`."
  [code]
  (boolean (re-matches #"[A-Za-z][A-Za-z0-9]*" code)))

(defn- emit-fn [code]
  (str "(defn " code "\n"
       "  \"" code " (live rate): (" code ") => 1 " code "; (" code " amount) => that many " code ";\n"
       "  (" code " a b …) => a·b·… " code "^n (arity → exponent, like a unit).\"\n"
       "  ([]           (r/of \"" code "\"))\n"
       "  ([amount]     (r/of \"" code "\" amount))\n"
       "  ([a b & more] (reduce q/qmul (r/of \"" code "\" a) (map #(r/of \"" code "\" %) (cons b more)))))\n"))

(def ^:private header
  (str ";;;; commensura — Frink-inspired exact unit conversion for Clojure.\n"
       ";;;; Copyright (C) 2026  crinklywrappr — GPL-3.0-or-later.\n"
       ";;;;\n"
       ";;;; GENERATED by commensura.currency.gen from resources/commensura/currency-codes.edn.\n"
       ";;;; Do not edit by hand — re-run `clojure -X:build gen-currency`.\n\n"
       "(ns commensura.currency\n"
       "  \"Discoverable currency units — live rates via CurrencyFreaks (needs CURRENCYFREAKS_API_KEY).\n"
       "  One fn per code: `(EUR)` => 1 EUR, `(EUR 600)` => 600 EUR, `(EUR 3 5)` => 15 EUR^2 (arity ->\n"
       "  exponent, as for a unit); compose with the core verbs, e.g. `(c/to (EUR 600) u/dollar)`. Codes\n"
       "  without a legal symbol name, and dynamic use, go through `commensura.currency.rates/of`.\"\n"
       "  (:require [commensura.currency.rates :as r]\n"
       "            [commensura.quantity :as q]))\n\n"))

(defn generate!
  "Build task entry (clojure -X:build gen-currency): regenerate src/commensura/currency.clj."
  [& _]
  (let [codes (sort (edn/read-string (slurp codes-path)))
        legal (filter legal-sym? codes)]
    (spit out-path (str header (str/join "\n" (map emit-fn legal))))
    (println "wrote" out-path "-" (count legal) "of" (count codes)
             "codes (skipped" (- (count codes) (count legal)) "non-symbol codes)")))
